### PR TITLE
add basic component methods

### PR DESCRIPTION
**Pull request by cangus**

### CODE REVIEW

**Comment by AstroMatt** [comment]
Thanks! :)

**Comment by cangus** [comment]
Thank you - this project saved me a bunch of time.
I don't see the changes reflected in master yet - is it hiding in a local branch?

**Comment by AstroMatt** [comment]
I have merged to the master branch and you should be able to git pull
Although there is some problem with github website and it does not display
the changes.
I have filed a bug report earlier today.
The git repo underneath is ok

**Comment by AstroMatt** [comment]
It's always nice to hear that :)
I have a bit more time now, so maybe I will worke a little more on this
project

**Pull request closed without merging**
